### ISSUE TITLE
The exporter requires to run as "root" to work

### ISSUE THREAD

**Issue by kodachimaru** [mehdy/keepalived-exporter#82]
If I run it as a non root user, I get this error

```text
prometheus@pgsyncslave:/home/sosuna/keepalived-exporter-1.0.0.linux-amd64$ curl localhost:9165/metrics
ERRO[0010] Failed to send signal                         error="operation not permitted" pid=12008
ERRO[0010] Failed to send STATS signal to keepalived     error="operation not permitted"
ERRO[0010] No data found to be exported                  error="operation not permitted" json=false
```

And the only metric returned is

```text
keepalived_up 0
```

If I run it as "root" instead, the exporter works just fine. But obviously I don't wanna run it as root...

**Comment by kodachimaru** [comment]
I am running keepalived as root, maybe it could be because of that?

**Comment by mehdy** [comment]
@kodachimaru 
That's correct. Since you're running keepalived as root the files that keepalived creates are owned by the root users.
I recommend running keepalived and keepalived-exporter as non-root users with a shared group.

Sorry for the long delay.
Feel free to reopen if it didn't solve your problem.
