### ISSUE TITLE
keepalived_vrrp_state value doesn't update

### ISSUE THREAD

**Issue by pruza33** [mehdy/keepalived-exporter#86]
Hello, when i stop the keepalived service on my primary server (keepalived-01), the value of old master stay on 2 on grafana, but i would like to change in 0 for became in fault state. How to do it ?

![image](https://user-images.githubusercontent.com/93667685/207577409-0f689f0c-97a0-41d9-8e71-bf45205979e7.png)

**Comment by mehdy** [comment]
Sorry for the delay. I'll investigate and get back to you.

**Comment by mehdy** [comment]
As far as I checked `keepalived-exporter` no longer exports `keepalived_vrrp_state` if the `keepalived` is not running.
And it seems like that the metrics providing correct data in your case as well (since the graph line has dropped on `keepalived-01` when the graph line on `keepalived-02` has risen.) and it may be a grafana configuration issue that still shows `Master`.

P.S. you could check the `keepalived_up` metrics to see if the `keepalived` service is running or not.

I'll close the issue but feel free to open it again if you think there is more to it.
